In [3]:
import numpy as np

In [5]:
x = [1,5]

In [6]:
x = np.array(x)

In [7]:
x

array([1, 5])

In [8]:
x+1

array([2, 6])

In [10]:
y = np.array([5,6])

In [11]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.random.random([3,3])

array([[0.99412947, 0.6468544 , 0.81333669],
       [0.21278485, 0.51033112, 0.43262276],
       [0.50717237, 0.5537093 , 0.94380463]])